"""two  migration

Revision ID: 3fe656c09cc7
Revises: c392d51ab9bc
Create Date: 2024-05-11 15:24:33.544430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe656c09cc7'
down_revision = 'c392d51ab9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cats', 'description')
    # ### end Alembic commands ###
